In [1]:
import numpy as np
import pickle
import sys

In [2]:
with open("/Users/msharma/workspace/DPVI-code/uai17-code/logistic/abalone/data/aba.p", "rb") as file:
    data = pickle.load(file, encoding='latin1')
    
np.set_printoptions(threshold=sys.maxsize)

In [6]:
y = data[0]
x = data[1]
print(x[0:5, :])
print(y[0:5])
print(x.shape)

[[ 1.15434629 -0.57455813 -0.43214879 -1.06442415 -0.64189823 -0.60768536
  -0.72621157 -0.63821689]
 [ 1.15434629 -1.44898585 -1.439929   -1.18397831 -1.23027711 -1.17090984
  -1.20522124 -1.21298732]
 [-0.05379815  0.05003309  0.12213032 -0.10799087 -0.30946926 -0.4634999
  -0.35668983 -0.20713907]
 [ 1.15434629 -0.69947638 -0.43214879 -0.34709919 -0.63781934 -0.64823753
  -0.60759966 -0.60229374]
 [-1.26194258 -1.61554351 -1.54070702 -1.42308663 -1.27208566 -1.2159678
  -1.28733718 -1.32075677]]
[1 0 0 1 0]
(4177, 8)


`-5.745581331424136629e-01,-4.321487936470637115e-01,-1.064424146726695719e+00,-6.418982280024725373e-01,-6.076853645006242699e-01,-7.262115735818162054e-01,-6.382168891980077863e-01,1.151980110023283377e+00`

In [32]:
print(np.mean(x, axis=0))
print(np.std(x, axis=0))

[ 2.57129460e-16 -4.23872891e-15 -1.38928052e-14  2.49190182e-14
 -4.96333748e-15  4.60015608e-15 -2.83852424e-15  8.18646616e-16]
[1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
with open("/Users/msharma/workspace/DPVI-code/uai17-code/logistic/adult/data/adult.p", "rb") as file:
    data = pickle.load(file, encoding='latin1')

y = data[0]
x = data[1]
print(x[0, :])
print(np.mean(x, axis=0))
print(np.std(x, axis=0))
print(y[:10])

[ 0.03067056  2.15057856 -1.06361075 -0.33543693  1.13473876  0.92163395
 -1.3178091  -0.27780504  0.39366753  0.70307135  0.1484529  -0.21665953
 -0.03542945  0.29156857]
[-1.00278429e-17 -4.28599074e-16 -1.15574213e-16 -1.54437645e-16
  3.24491584e-16  2.81613265e-16  2.28894634e-16  4.26236172e-16
  1.17145731e-15  5.71992794e-16  7.13712366e-17 -1.53672174e-15
 -4.31311041e-16  1.00490510e-15]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]


In [36]:
with open("/Users/msharma/workspace/DPVI-code/uai17-code/logistic/abalone/data/abalone_ndp.p", "rb") as file:
    data = pickle.load(file, encoding='latin1')

In [37]:
print(data)

[0.7667464114832536]


In [39]:
x[0, :]

array([ 0.03067056,  2.15057856, -1.06361075, -0.33543693,  1.13473876,
        0.92163395, -1.3178091 , -0.27780504,  0.39366753,  0.70307135,
        0.1484529 , -0.21665953, -0.03542945,  0.29156857])