In [67]:
# add files that we need!
import os
import sys

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
print(sys.path)

# autoreloading
%load_ext autoreload
%autoreload 2

['/Users/msharma/workspace/DP-PVI/notebooks', '/Users/msharma/.local/share/virtualenvs/DP-PVI-uFKN1QRX/lib/python37.zip', '/Users/msharma/.local/share/virtualenvs/DP-PVI-uFKN1QRX/lib/python3.7', '/Users/msharma/.local/share/virtualenvs/DP-PVI-uFKN1QRX/lib/python3.7/lib-dynload', '/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '', '/Users/msharma/.local/share/virtualenvs/DP-PVI-uFKN1QRX/lib/python3.7/site-packages', '/Users/msharma/.local/share/virtualenvs/DP-PVI-uFKN1QRX/lib/python3.7/site-packages/IPython/extensions', '/Users/msharma/.ipython', '/Users/msharma/workspace/DP-PVI']
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [68]:
from src.model.logistic_regression_models import MeanFieldMultiDimensionalLogisticRegression
import torch

In [69]:
prior_mean = torch.tensor([1, 1], dtype=torch.float64)
prior_var = torch.log(torch.tensor([1, 0.5], dtype=torch.float64))

hyperparameters = {
    "prior_mu": prior_mean,
    "prior_log_var": prior_var,
    "N_samples": 50,
    "N_steps": 2000,
    "learning_rate": 0.01
}

logRegressionModel = MeanFieldMultiDimensionalLogisticRegression(None, hyperparameters, 2)

In [70]:
data_x = torch.tensor([[2, 2], [1, 1], [-1, -1], [-2, -2]], dtype=torch.float64)
data_y = torch.tensor([1, 1, -1, -1], dtype=torch.float64)
data = {
    "X": data_x,
    "y": data_y,
}

t = {
    'w_mu': torch.tensor([0, 0], dtype=torch.float64),
    'w_log_var': torch.tensor([0, 0], dtype=torch.float64)
}

init_params = {
    "w_mu": prior_mean,
    "w_log_var": torch.tensor([1, 1], dtype=torch.float64),
}

In [71]:
# note that these 
print(list(logRegressionModel.parameters()))

[Parameter containing:
tensor([ 0.0613, -0.0307], dtype=torch.float64, requires_grad=True), Parameter containing:
tensor([-0.0844,  0.0069], dtype=torch.float64, requires_grad=True)]


In [72]:
logRegressionModel.fit(data, t, None, hyperparameters)

tensor(4.5707, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.8359, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.7931, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.9787, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.6971, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.8841, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.8660, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.7947, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.9602, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.6225, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.4282, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.8643, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.6616, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.3754, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.8172, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.9219, dtype=torch.float64, grad_fn=<NegBackward>)
tensor(3.6165, dtype=torch.float64, grad_fn=<NegBackward

{'w_mu': Parameter containing:
 tensor([0.5961, 0.5041], dtype=torch.float64, requires_grad=True),
 'w_log_var': Parameter containing:
 tensor([-2.4896, -2.4817], dtype=torch.float64, requires_grad=True)}

In [ ]:
print(logRegressionModel.update_hyperparameters())