In [153]:
# add files that we need!
import os
import sys

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
print(sys.path)

# autoreloading
%load_ext autoreload
%autoreload 2

['/Users/msharma/workspace/DP-PVI/notebooks', '/Users/msharma/.local/share/virtualenvs/DP-PVI-uFKN1QRX/lib/python37.zip', '/Users/msharma/.local/share/virtualenvs/DP-PVI-uFKN1QRX/lib/python3.7', '/Users/msharma/.local/share/virtualenvs/DP-PVI-uFKN1QRX/lib/python3.7/lib-dynload', '/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '', '/Users/msharma/.local/share/virtualenvs/DP-PVI-uFKN1QRX/lib/python3.7/site-packages', '/Users/msharma/.local/share/virtualenvs/DP-PVI-uFKN1QRX/lib/python3.7/site-packages/IPython/extensions', '/Users/msharma/.ipython', '/Users/msharma/workspace/DP-PVI']
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [166]:
from src.model.logistic_regression_models import MeanFieldMultiDimensionalLogisticRegression
import torch

In [167]:
prior_mean = torch.tensor([1, 1], dtype=torch.float64)
prior_var = torch.log(torch.tensor([[1, 0.5], [0.5, 1]], dtype=torch.float64))

hyperparameters = {
    "prior_mu": prior_mean,
    "prior_log_var_mat": prior_var,
}

logRegressionModel = MeanFieldMultiDimensionalLogisticRegression(None, hyperparameters, 2)

In [209]:
data_x = torch.tensor([[2, 2], [1, 1], [-1, -1], [-2, -2]], dtype=torch.float64)
data_y = torch.tensor([1, 1, -1, -1], dtype=torch.float64)

# run the network forwards and compute the stochastic elbo
Y, act_mat = logRegressionModel.forward(data_x, 10)
elbopp = logRegressionModel.compute_ELBO_loss_per_point(act_mat, data_y)
print(elbopp)

tensor([-1.5900, -0.9238, -0.6224, -1.0022], dtype=torch.float64,
       grad_fn=<AddBackward0>)


In [212]:
for i in range(4):
    elbopp[i].backward(retain_graph=True)
    params = logRegressionModel.get_parameters()
    print(params["w_mu"].grad)
    print(params["w_log_var"].grad)

tensor([14.6976, 13.9552], dtype=torch.float64)
tensor([-3.0516, -3.0455], dtype=torch.float64)
tensor([15.0718, 14.2940], dtype=torch.float64)
tensor([-3.1563, -3.1505], dtype=torch.float64)
tensor([15.4217, 14.6087], dtype=torch.float64)
tensor([-3.1876, -3.1832], dtype=torch.float64)
tensor([16.3616, 15.5131], dtype=torch.float64)
tensor([-3.3381, -3.3332], dtype=torch.float64)


tensor([[ 0.1441,  0.8793, -1.9183, -2.7773, -6.6147,  0.6691,  3.2370,  3.4455,
         -0.3904,  1.3841],
        [ 0.0721,  0.4396, -0.9591, -1.3886, -3.3074,  0.3346,  1.6185,  1.7228,
         -0.1952,  0.6921],
        [ 0.0540, -0.3136,  1.0852,  1.5147,  3.4334, -0.2085, -1.4925, -1.5967,
          0.3212, -0.5660],
        [ 0.1079, -0.6273,  2.1703,  3.0293,  6.8668, -0.4171, -2.9850, -3.1935,
          0.6424, -1.1321]], dtype=torch.float64, grad_fn=<MulBackward0>)

tensor([[ 0.1441,  0.8793, -1.9183, -2.7773, -6.6147,  0.6691,  3.2370,  3.4455,
         -0.3904,  1.3841],
        [ 0.0721,  0.4396, -0.9591, -1.3886, -3.3074,  0.3346,  1.6185,  1.7228,
         -0.1952,  0.6921],
        [-0.0540,  0.3136, -1.0852, -1.5147, -3.4334,  0.2085,  1.4925,  1.5967,
         -0.3212,  0.5660],
        [-0.1079,  0.6273, -2.1703, -3.0293, -6.8668,  0.4171,  2.9850,  3.1935,
         -0.6424,  1.1321]], dtype=torch.float64, grad_fn=<AddBackward0>)